services:
  - type: web
    name: eviltech-apk-builder
    runtime: docker
    plan: starter
    healthCheckPath: /health
    envVars:
      - key: EVITECH_DB_URL
        fromDatabase:
          name: eviltech
          property: connectionString

databases:
  - name: eviltech
    databaseName: eviltech
    plan: free
